export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGOUT = 'LOGOUT'

export const APPROVE_APPLY = 'APPROVE'
export const REJECT_APPLY = 'REJECT'

export const FETCHING_APPLIES_DATA = 'FETCHING_DATA'
export const FETCHING_APPLIES_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'
export const FETCHING_APPLIES_DATA_FAILURE = 'FETCHING_DATA_FAILURE'

