export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGOUT = 'LOGOUT'

export const UPGRADE_USER_START = "UPGRADE_USER_START"
export const UPGRADE_USER_SUCCESS = "UPGRADE_USER_SUCCESS"
export const UPGRADE_USER_ERROR = "UPGRADE_USER_ERROR"
